version: "3.9"

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${CODE_PASSWORD}
    volumes:
      - ./config/code-server:/config
      - ./projekty:/projekty
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    volumes:
      - ./gitea:/data
    restart: unless-stopped

  flask:
    build: ./flask-app
    container_name: flask-app
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - code-server
      - adminer
      - portainer
      - gitea
      - flask
    restart: unless-stopped

volumes:
  portainer_data: